import { GameConfig, TCGGame } from "@/types";

export const GAMES: GameConfig[] = [
  {
    id: "yugioh",
    name: "Yu-Gi-Oh!",
    shortName: "YGO",
    icon: "⚔️",
    color: "#8B4513",
    gradient: "from-yellow-900 via-yellow-700 to-yellow-500",
    deckSize: { min: 40, max: 60 },
    extraDeckSize: 15,
    openingHandSize: 5,
    description: "The classic duel monsters card game",
  },
  {
    id: "onepiece",
    name: "One Piece Card Game",
    shortName: "OPCG",
    icon: "🏴‍☠️",
    color: "#DC2626",
    gradient: "from-red-900 via-red-700 to-orange-500",
    deckSize: { min: 50, max: 50 },
    openingHandSize: 5,
    description: "Set sail for the Grand Line",
  },
  {
    id: "digimon",
    name: "Digimon Card Game",
    shortName: "DCG",
    icon: "🦕",
    color: "#2563EB",
    gradient: "from-blue-900 via-blue-700 to-cyan-500",
    deckSize: { min: 50, max: 50 },
    openingHandSize: 5,
    description: "Digivolve your way to victory",
  },
  {
    id: "gundam",
    name: "Gundam Card Game",
    shortName: "GCG",
    icon: "🤖",
    color: "#4B5563",
    gradient: "from-gray-900 via-gray-700 to-blue-600",
    deckSize: { min: 50, max: 50 },
    openingHandSize: 5,
    description: "Mobile suit tactical battles",
  },
  {
    id: "dbs",
    name: "Dragon Ball Super Card Game",
    shortName: "DBS",
    icon: "🐉",
    color: "#F59E0B",
    gradient: "from-orange-900 via-orange-600 to-yellow-400",
    deckSize: { min: 50, max: 60 },
    openingHandSize: 6,
    description: "Power levels over 9000",
  },
  {
    id: "dbsfusion",
    name: "DBS Fusion World",
    shortName: "DBSFW",
    icon: "✨",
    color: "#7C3AED",
    gradient: "from-purple-900 via-purple-700 to-pink-500",
    deckSize: { min: 50, max: 60 },
    openingHandSize: 6,
    description: "Fusion warriors unite",
  },
  {
    id: "pokemon",
    name: "Pokémon TCG",
    shortName: "PTG",
    icon: "⚡",
    color: "#EAB308",
    gradient: "from-yellow-700 via-yellow-500 to-red-500",
    deckSize: { min: 60, max: 60 },
    openingHandSize: 7,
    description: "Gotta catch 'em all",
  },
  {
    id: "unionarena",
    name: "Union Arena",
    shortName: "UA",
    icon: "🌀",
    color: "#059669",
    gradient: "from-emerald-900 via-emerald-700 to-teal-500",
    deckSize: { min: 50, max: 50 },
    openingHandSize: 5,
    description: "Unite your favorite anime fighters",
  },
  {
    id: "mtg",
    name: "Magic: The Gathering",
    shortName: "MTG",
    icon: "🔮",
    color: "#6366F1",
    gradient: "from-indigo-900 via-indigo-700 to-violet-500",
    deckSize: { min: 60, max: 250 },
    openingHandSize: 7,
    description: "The original trading card game",
  },
  {
    id: "lorcana",
    name: "Disney Lorcana",
    shortName: "LOR",
    icon: "✨",
    color: "#8B5CF6",
    gradient: "from-purple-900 via-violet-700 to-indigo-500",
    deckSize: { min: 60, max: 60 },
    openingHandSize: 7,
    description: "Illumineer your way to glory",
  },
  {
    id: "swu",
    name: "Star Wars: Unlimited",
    shortName: "SWU",
    icon: "⚔️",
    color: "#FFE81F",
    gradient: "from-gray-900 via-yellow-900 to-yellow-600",
    deckSize: { min: 50, max: 50 },
    openingHandSize: 6,
    description: "May the Force be with you",
  },
  {
    id: "riftbound",
    name: "Riftbound",
    shortName: "RFT",
    icon: "💎",
    color: "#06B6D4",
    gradient: "from-cyan-900 via-cyan-700 to-blue-500",
    deckSize: { min: 40, max: 40 },
    openingHandSize: 5,
    description: "Champions battle across the Rift",
  },
];

export function getGame(id: TCGGame): GameConfig {
  return GAMES.find((g) => g.id === id) || GAMES[0];
}
