import { Card } from "@/types";

export const ONEPIECE_CARDS: Card[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // OP01 LEADERS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_001",
    name: "Roronoa Zoro",
    game: "onepiece",
    type: "Leader",
    color: "Red",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 5,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["leader", "straw-hat"],
    description: "Leader – Supernovas/Straw Hat Crew.",
  },
  {
    id: "op-op01_002",
    name: "Trafalgar Law",
    game: "onepiece",
    type: "Leader",
    color: "Red/Green",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 4,
    archetype: ["Supernovas", "Heart Pirates"],
    tags: ["leader", "heart-pirates"],
    description: "Leader – Supernovas/Heart Pirates.",
  },
  {
    id: "op-op01_003",
    name: "Monkey.D.Luffy",
    game: "onepiece",
    type: "Leader",
    color: "Red/Green",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 4,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["leader", "straw-hat"],
    description: "Leader – Supernovas/Straw Hat Crew.",
  },
  {
    id: "op-op01_031",
    name: "Kozuki Oden",
    game: "onepiece",
    type: "Leader",
    color: "Green",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 5,
    archetype: ["Land of Wano", "Kozuki Clan"],
    tags: ["leader", "land-of-wano"],
    description: "Leader – Land of Wano/Kozuki Clan.",
  },
  {
    id: "op-op01_060",
    name: "Donquixote Doflamingo",
    game: "onepiece",
    type: "Leader",
    color: "Blue",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 5,
    archetype: ["The Seven Warlords of the Sea", "Donquixote Pirates"],
    tags: ["leader", "seven-warlords"],
    description: "Leader – The Seven Warlords of the Sea/Donquixote Pirates.",
  },
  {
    id: "op-op01_061",
    name: "Kaido",
    game: "onepiece",
    type: "Leader",
    color: "Blue/Purple",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 4,
    archetype: ["The Four Emperors", "Animal Kingdom Pirates"],
    tags: ["leader", "four-emperors", "animal-kingdom"],
    description: "Leader – The Four Emperors/Animal Kingdom Pirates.",
  },
  {
    id: "op-op01_062",
    name: "Crocodile",
    game: "onepiece",
    type: "Leader",
    color: "Blue/Purple",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 4,
    archetype: ["The Seven Warlords of the Sea", "Baroque Works"],
    tags: ["leader", "seven-warlords", "baroque-works"],
    description: "Leader – The Seven Warlords of the Sea/Baroque Works.",
  },
  {
    id: "op-op01_091",
    name: "King",
    game: "onepiece",
    type: "Leader",
    color: "Purple",
    rarity: "Leader",
    set: "OP-01",
    setCode: "OP01",
    power: 5000,
    life: 5,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["leader", "animal-kingdom"],
    description: "Leader – Animal Kingdom Pirates.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 RED CHARACTERS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_004",
    name: "Usopp",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Straw Hat Crew"],
    tags: ["draw", "straw-hat"],
    description: "Ranged. Counter +2000. Draw when opponent activates an Event.",
  },
  {
    id: "op-op01_005",
    name: "Uta",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 4000,
    archetype: ["FILM"],
    tags: [],
    description: "Special. Add a red Character cost 3 or less from trash to hand.",
  },
  {
    id: "op-op01_006",
    name: "Otama",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 0,
    archetype: ["Land of Wano"],
    tags: ["land-of-wano"],
    description: "Special. Counter +2000. Give one opponent's Character -2000 power.",
  },
  {
    id: "op-op01_007",
    name: "Caribou",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Supernovas", "Caribou Pirates"],
    tags: ["removal"],
    description: "Special. Counter +1000. KO an opponent's Character cost 4 or less on KO.",
  },
  {
    id: "op-op01_008",
    name: "Cavendish",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Supernovas", "Beautiful Pirates"],
    tags: ["rush"],
    description: "Slash. Rush if you add a Life card to your hand.",
  },
  {
    id: "op-op01_009",
    name: "Carrot",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Minks"],
    tags: [],
    description: "Strike. Counter +1000. Trigger: play this card.",
  },
  {
    id: "op-op01_010",
    name: "Komachiyo",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 3000,
    archetype: ["Animal", "Land of Wano"],
    tags: ["land-of-wano"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_011",
    name: "Gordon",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["FILM"],
    tags: ["draw"],
    description: "Wisdom. Counter +2000. Discard a card to draw a card.",
  },
  {
    id: "op-op01_012",
    name: "Sai",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 4000,
    archetype: ["Happosui Army"],
    tags: [],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-op01_013",
    name: "Sanji",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Strike. Counter +2000. Give this Character +2000 power when you attach a DON!! card.",
  },
  {
    id: "op-op01_014",
    name: "Jinbe",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Fish-Man", "Straw Hat Crew"],
    tags: ["blocker", "straw-hat"],
    description: "Strike. Blocker. On play, play a red Character cost 2 or less.",
  },
  {
    id: "op-op01_015",
    name: "Tony Tony.Chopper",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Animal", "Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Wisdom. Counter +1000. Recover a Straw Hat Crew Character from trash.",
  },
  {
    id: "op-op01_016",
    name: "Nami",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 2000,
    archetype: ["Straw Hat Crew"],
    tags: ["search", "straw-hat"],
    description: "Special. Counter +1000. Search deck for a Straw Hat Crew card.",
  },
  {
    id: "op-op01_017",
    name: "Nico Robin",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Straw Hat Crew"],
    tags: ["removal", "straw-hat"],
    description: "Strike. Counter +1000. KO a Character with 3000 or less power when attacking.",
  },
  {
    id: "op-op01_018",
    name: "Hajrudin",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 6000,
    archetype: ["Giant", "New Giant Pirates"],
    tags: [],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_019",
    name: "Bartolomeo",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 2000,
    archetype: ["Supernovas", "Barto Club"],
    tags: ["blocker"],
    description: "Special. Counter +1000. Blocker. Gains +3000 power during opponent's turn.",
  },
  {
    id: "op-op01_020",
    name: "Hyogoro",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Land of Wano"],
    tags: ["land-of-wano"],
    description: "Strike. Counter +1000. Rest to give a Character +2000 power.",
  },
  {
    id: "op-op01_021",
    name: "Franky",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Ranged. Can attack active Characters.",
  },
  {
    id: "op-op01_022",
    name: "Brook",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Slash. Counter +1000. Give 2 opponent Characters -2000 power.",
  },
  {
    id: "op-op01_023",
    name: "Marco",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    archetype: ["Former Whitebeard Pirates"],
    tags: [],
    description: "Special. Counter +1000.",
  },
  {
    id: "op-op01_024",
    name: "Monkey.D.Luffy",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Strike. Counter +1000. Cannot be KO'd by Strike effects; gains power when given DON!!.",
  },
  {
    id: "op-op01_025",
    name: "Roronoa Zoro",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["rush", "straw-hat"],
    description: "Slash. Rush.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 RED EVENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_026",
    name: "Gum-Gum Fire-Fist Pistol Red Hawk",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["removal", "straw-hat"],
    description: "Give a Character +4000 power; KO a Character cost 4 or less.",
  },
  {
    id: "op-op01_027",
    name: "Round Table",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    archetype: ["Supernovas", "Beautiful Pirates"],
    tags: [],
    description: "Give one Character -10000 power until end of turn.",
  },
  {
    id: "op-op01_028",
    name: "Green Star Rafflesia",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Give one Character -2000 power until end of turn.",
  },
  {
    id: "op-op01_029",
    name: "Radical Beam!!",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Give a Character +2000 power; +2000 additional power if you have 2 or fewer Life cards.",
  },
  {
    id: "op-op01_030",
    name: "In Two Years!! At the Sabaody Archipelago!!",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Straw Hat Crew"],
    tags: ["search", "straw-hat"],
    description: "Search deck for a Straw Hat Crew Character and add it to your hand.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 GREEN CHARACTERS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_032",
    name: "Ashura Doji",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["land-of-wano"],
    description: "Slash. Counter +1000. Gains +2000 power if opponent has 2 or more rested Characters.",
  },
  {
    id: "op-op01_033",
    name: "Izo",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 3000,
    archetype: ["Land of Wano", "Former Whitebeard Pirates"],
    tags: ["land-of-wano"],
    description: "Ranged. Counter +2000. Rest an opponent's Character cost 4 or less.",
  },
  {
    id: "op-op01_034",
    name: "Dog Storm",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Minks", "Land of Wano"],
    tags: ["land-of-wano"],
    description: "Slash. Counter +1000. Set a DON!! card as active when attacking.",
  },
  {
    id: "op-op01_035",
    name: "Okiku",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["land-of-wano"],
    description: "Slash. Rest an opponent's Character cost 5 or less when attacking.",
  },
  {
    id: "op-op01_036",
    name: "Otsuru",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 3000,
    archetype: ["Land of Wano"],
    tags: ["land-of-wano"],
    description: "Wisdom. Counter +1000.",
  },
  {
    id: "op-op01_037",
    name: "Kawamatsu",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Fish-Man", "Land of Wano"],
    tags: ["land-of-wano"],
    description: "Slash. Counter +1000. Trigger: play this card.",
  },
  {
    id: "op-op01_038",
    name: "Kanjuro",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["removal", "land-of-wano"],
    description: "Slash. Counter +1000. When attacking a rested Character, opponent must trash a card.",
  },
  {
    id: "op-op01_039",
    name: "Killer",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 2000,
    archetype: ["Supernovas", "Kid Pirates"],
    tags: ["blocker", "draw", "kid-pirates"],
    description: "Slash. Counter +1000. Blocker. Draw a card when this card blocks.",
  },
  {
    id: "op-op01_040",
    name: "Kin'emon",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 6,
    power: 6000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["land-of-wano"],
    description: "Slash. Play an Akazaya Nine Character cost 3 or less and set it active.",
  },
  {
    id: "op-op01_041",
    name: "Momonosuke",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 0,
    archetype: ["Land of Wano", "Kozuki Clan"],
    tags: ["search", "land-of-wano"],
    description: "Slash. Counter +1000. Search deck for a Land of Wano card.",
  },
  {
    id: "op-op01_042",
    name: "Komurasaki",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 0,
    archetype: ["Land of Wano", "Kozuki Clan"],
    tags: ["land-of-wano"],
    description: "Wisdom. Counter +1000. Set a Land of Wano Character as active if you have an Oden Leader.",
  },
  {
    id: "op-op01_043",
    name: "Shinobu",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    archetype: ["Land of Wano"],
    tags: ["land-of-wano"],
    description: "Special. Counter +1000.",
  },
  {
    id: "op-op01_044",
    name: "Shachi",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Heart Pirates"],
    tags: ["blocker", "heart-pirates"],
    description: "Strike. Counter +1000. Blocker. On play, play Penguin.",
  },
  {
    id: "op-op01_045",
    name: "Jean Bart",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 6000,
    archetype: ["Heart Pirates"],
    tags: ["heart-pirates"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_046",
    name: "Denjiro",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 7000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["land-of-wano"],
    description: "Slash. Set up to 2 DON!! cards active if you have an Oden Leader.",
  },
  {
    id: "op-op01_047",
    name: "Trafalgar Law",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 6000,
    archetype: ["Supernovas", "Heart Pirates"],
    tags: ["blocker", "heart-pirates"],
    description: "Slash. Blocker. Bounce a Character; play a Character cost 3 or less.",
  },
  {
    id: "op-op01_048",
    name: "Nekomamushi",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Minks", "Land of Wano"],
    tags: ["land-of-wano"],
    description: "Slash. Counter +1000. Rest an opponent's Character cost 3 or less.",
  },
  {
    id: "op-op01_049",
    name: "Bepo",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 4000,
    archetype: ["Minks", "Heart Pirates"],
    tags: ["heart-pirates"],
    description: "Strike. Counter +2000. Play a Heart Pirates Character cost 4 or less when attacking.",
  },
  {
    id: "op-op01_050",
    name: "Penguin",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 2000,
    archetype: ["Heart Pirates"],
    tags: ["blocker", "heart-pirates"],
    description: "Strike. Counter +1000. Blocker. On play, play Shachi.",
  },
  {
    id: "op-op01_051",
    name: "Eustass Captain Kid",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 8,
    power: 8000,
    archetype: ["Supernovas", "Kid Pirates"],
    tags: ["boss", "kid-pirates"],
    description: "Special. Opponent must attack this Character if it is rested. On play, play a Character cost 3 or less.",
  },
  {
    id: "op-op01_052",
    name: "Raizo",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Land of Wano", "The Akazaya Nine"],
    tags: ["draw", "land-of-wano"],
    description: "Slash. Counter +1000. Draw when attacking if 2 or more Characters are rested.",
  },
  {
    id: "op-op01_053",
    name: "Wire",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 4000,
    archetype: ["Kid Pirates"],
    tags: ["kid-pirates"],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-op01_054",
    name: "X.Drake",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 6000,
    archetype: ["Supernovas", "Drake Pirates"],
    tags: ["removal"],
    description: "Slash. Counter +1000. KO a rested Character cost 4 or less on play.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 GREEN EVENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_055",
    name: "You Can Be My Samurai!",
    game: "onepiece",
    type: "Event",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Land of Wano", "Kozuki Clan"],
    tags: ["draw", "land-of-wano"],
    description: "Rest 2 Characters to draw 2 cards.",
  },
  {
    id: "op-op01_056",
    name: "Demon Face",
    game: "onepiece",
    type: "Event",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 6,
    archetype: ["Supernovas", "Hawkins Pirates"],
    tags: ["removal"],
    description: "KO 2 rested Characters cost 5 or less.",
  },
  {
    id: "op-op01_057",
    name: "Paradise Waterfall",
    game: "onepiece",
    type: "Event",
    color: "Green",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Land of Wano", "Kozuki Clan"],
    tags: ["land-of-wano"],
    description: "Give a Character +2000 power and set it as active.",
  },
  {
    id: "op-op01_058",
    name: "Punk Gibson",
    game: "onepiece",
    type: "Event",
    color: "Green",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["Supernovas", "Kid Pirates"],
    tags: ["kid-pirates"],
    description: "Give a Character +4000 power; rest an opponent's Character cost 4 or less.",
  },
  {
    id: "op-op01_059",
    name: "Beben!!",
    game: "onepiece",
    type: "Event",
    color: "Green",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    archetype: ["Land of Wano"],
    tags: ["land-of-wano"],
    description: "Trash a Land of Wano card to set Characters active.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 BLUE CHARACTERS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_063",
    name: "Arlong",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Fish-Man", "Arlong Pirates"],
    tags: [],
    description: "Slash. Counter +1000. Hand disruption effect.",
  },
  {
    id: "op-op01_064",
    name: "Alvida",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Buggy Pirates"],
    tags: [],
    description: "Strike. Counter +2000. Bounce a Character cost 3 or less when attacking.",
  },
  {
    id: "op-op01_065",
    name: "Vergo",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 7000,
    archetype: ["Navy", "Donquixote Pirates"],
    tags: ["navy"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_066",
    name: "Krieg",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 6000,
    archetype: ["Krieg Pirates"],
    tags: [],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-op01_067",
    name: "Crocodile",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 7,
    power: 7000,
    archetype: ["The Seven Warlords of the Sea", "Baroque Works"],
    tags: ["seven-warlords", "baroque-works"],
    description: "Special. Counter +1000. Reduce cost of blue Events by 1.",
  },
  {
    id: "op-op01_068",
    name: "Gecko Moria",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["The Seven Warlords of the Sea", "Thriller Bark Pirates"],
    tags: ["seven-warlords"],
    description: "Special. Double Attack if you have 5 or more cards in hand.",
  },
  {
    id: "op-op01_069",
    name: "Caesar Clown",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Scientist", "Punk Hazard"],
    tags: [],
    description: "Special. Counter +1000. Play Smiley from deck when this card is KO'd.",
  },
  {
    id: "op-op01_070",
    name: "Dracule Mihawk",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 9,
    power: 9000,
    archetype: ["The Seven Warlords of the Sea"],
    tags: ["boss", "seven-warlords"],
    description: "Slash. Bounce an opponent's Character cost 7 or less on play.",
  },
  {
    id: "op-op01_071",
    name: "Jinbe",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 2000,
    archetype: ["Fish-Man", "Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Strike. Bounce an opponent's Character cost 3 or less on play.",
  },
  {
    id: "op-op01_072",
    name: "Smiley",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 1000,
    archetype: ["Biological Weapon", "Punk Hazard"],
    tags: [],
    description: "Special. Counter +1000. Gains +1000 power for each card in your hand.",
  },
  {
    id: "op-op01_073",
    name: "Donquixote Doflamingo",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["The Seven Warlords of the Sea", "Donquixote Pirates"],
    tags: ["blocker", "search", "seven-warlords"],
    description: "Special. Counter +1000. Blocker. Reorder top of deck when blocking.",
  },
  {
    id: "op-op01_074",
    name: "Bartholomew Kuma",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["The Seven Warlords of the Sea", "Revolutionary Army"],
    tags: ["blocker", "seven-warlords"],
    description: "Strike. Counter +1000. Blocker. Play a Pacifista from deck when KO'd.",
  },
  {
    id: "op-op01_075",
    name: "Pacifista",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Biological Weapon", "Navy"],
    tags: ["blocker", "navy"],
    description: "Special. Blocker.",
  },
  {
    id: "op-op01_076",
    name: "Bellamy",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 4000,
    archetype: ["Dressrosa"],
    tags: [],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_077",
    name: "Perona",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 2000,
    archetype: ["Thriller Bark Pirates"],
    tags: ["search"],
    description: "Special. Counter +1000. Look at the top 5 cards of your deck and reorder them.",
  },
  {
    id: "op-op01_078",
    name: "Boa Hancock",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["The Seven Warlords of the Sea", "Kuja Pirates"],
    tags: ["blocker", "draw", "seven-warlords"],
    description: "Special. Counter +1000. Blocker. Draw a card when attacking or blocking.",
  },
  {
    id: "op-op01_079",
    name: "Ms All Sunday",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 1000,
    archetype: ["Baroque Works"],
    tags: ["blocker", "baroque-works"],
    description: "Strike. Counter +1000. Blocker. Add an Event from trash to hand.",
  },
  {
    id: "op-op01_080",
    name: "Miss Doublefinger(Zala)",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Baroque Works"],
    tags: ["draw", "baroque-works"],
    description: "Slash. Counter +1000. Draw a card when KO'd.",
  },
  {
    id: "op-op01_081",
    name: "Mocha",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    archetype: ["Punk Hazard"],
    tags: [],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_082",
    name: "Monet",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Donquixote Pirates", "Punk Hazard"],
    tags: [],
    description: "Special. Counter +1000. Trigger: play this card.",
  },
  {
    id: "op-op01_083",
    name: "Mr.1(Daz.Bonez)",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Baroque Works"],
    tags: ["baroque-works"],
    description: "Slash. Counter +1000. Gains +1000 power for each Event in trash.",
  },
  {
    id: "op-op01_084",
    name: "Mr.2.Bon.Kurei(Bentham)",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Baroque Works"],
    tags: ["search", "baroque-works"],
    description: "Strike. Counter +2000. Search deck for a Baroque Works Event.",
  },
  {
    id: "op-op01_085",
    name: "Mr.3(Galdino)",
    game: "onepiece",
    type: "Character",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Baroque Works"],
    tags: ["baroque-works"],
    description: "Special. Counter +1000. Lock an opponent's Character.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 BLUE EVENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_086",
    name: "Overheat",
    game: "onepiece",
    type: "Event",
    color: "Blue",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["The Seven Warlords of the Sea", "Donquixote Pirates"],
    tags: ["seven-warlords"],
    description: "Give a Character +4000 power; bounce an active Character cost 3 or less.",
  },
  {
    id: "op-op01_087",
    name: "Officer Agents",
    game: "onepiece",
    type: "Event",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["Baroque Works"],
    tags: ["baroque-works"],
    description: "Play a Baroque Works Character cost 3 or less.",
  },
  {
    id: "op-op01_088",
    name: "Desert Spada",
    game: "onepiece",
    type: "Event",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["The Seven Warlords of the Sea", "Baroque Works"],
    tags: ["search", "seven-warlords", "baroque-works"],
    description: "Give a Character +2000 power; reorder top of deck.",
  },
  {
    id: "op-op01_089",
    name: "Crescent Cutlass",
    game: "onepiece",
    type: "Event",
    color: "Blue",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    archetype: ["The Seven Warlords of the Sea", "Baroque Works"],
    tags: ["seven-warlords", "baroque-works"],
    description: "Bounce an opponent's Character cost 5 or less.",
  },
  {
    id: "op-op01_090",
    name: "Baroque Works",
    game: "onepiece",
    type: "Event",
    color: "Blue",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Baroque Works"],
    tags: ["search", "baroque-works"],
    description: "Search deck for a Baroque Works card and add it to your hand.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 PURPLE CHARACTERS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_092",
    name: "Urashima",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 7,
    power: 9000,
    archetype: ["Land of Wano"],
    tags: ["boss", "land-of-wano"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op01_093",
    name: "Ulti",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["animal-kingdom"],
    description: "Strike. Add a rested DON!! card when played.",
  },
  {
    id: "op-op01_094",
    name: "Kaido",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 10,
    power: 12000,
    archetype: ["The Four Emperors", "Animal Kingdom Pirates"],
    tags: ["boss", "removal", "four-emperors", "animal-kingdom"],
    description: "Strike. Return 6 DON!! to deck to KO all other Characters.",
  },
  {
    id: "op-op01_095",
    name: "Kyoshirou",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 6000,
    archetype: ["Land of Wano"],
    tags: ["draw", "land-of-wano"],
    description: "Slash. Counter +1000. Draw a card if you have 8 or more DON!!.",
  },
  {
    id: "op-op01_096",
    name: "King",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Super Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 7,
    power: 7000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["removal", "animal-kingdom"],
    description: "Special. Return 2 DON!! to deck to KO opponent's Characters.",
  },
  {
    id: "op-op01_097",
    name: "Queen",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 6,
    power: 5000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["rush", "animal-kingdom"],
    description: "Strike. Counter +1000. Return 1 DON!! to deck for Rush and -2000 opponent power.",
  },
  {
    id: "op-op01_098",
    name: "Kurozumi Orochi",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    power: 2000,
    archetype: ["Land of Wano", "Kurozumi Clan"],
    tags: ["search", "land-of-wano"],
    description: "Wisdom. Counter +2000. Search deck for a SMILE card.",
  },
  {
    id: "op-op01_099",
    name: "Kurozumi Semimaru",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Land of Wano", "Kurozumi Clan"],
    tags: ["land-of-wano"],
    description: "Special. Counter +1000. Kurozumi Clan Characters cannot be KO'd.",
  },
  {
    id: "op-op01_100",
    name: "Kurozumi Higurashi",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Land of Wano", "Kurozumi Clan"],
    tags: ["blocker", "land-of-wano"],
    description: "Special. Counter +1000. Blocker.",
  },
  {
    id: "op-op01_101",
    name: "Sasaki",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["animal-kingdom"],
    description: "Slash. Counter +2000. Add a rested DON!! when attacking.",
  },
  {
    id: "op-op01_102",
    name: "Jack",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["animal-kingdom"],
    description: "Strike. Counter +1000. Opponent trashes a card when this attacks.",
  },
  {
    id: "op-op01_103",
    name: "Scratchmen Apoo",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 6000,
    archetype: ["Animal Kingdom Pirates", "On Air Pirates"],
    tags: ["animal-kingdom"],
    description: "Ranged. Counter +1000.",
  },
  {
    id: "op-op01_104",
    name: "Speed",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Strike. Counter +1000. Trigger: play this card.",
  },
  {
    id: "op-op01_105",
    name: "Bao Huang",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Wisdom. Counter +1000. Reveal 2 cards from opponent's hand.",
  },
  {
    id: "op-op01_106",
    name: "Basil Hawkins",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 2000,
    archetype: ["Animal Kingdom Pirates", "Hawkins Pirates"],
    tags: ["animal-kingdom"],
    description: "Slash. Counter +1000. Add a rested DON!!.",
  },
  {
    id: "op-op01_107",
    name: "Babanuki",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 7000,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Ranged. Counter +1000.",
  },
  {
    id: "op-op01_108",
    name: "Hitokiri Kamazo",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Supernovas", "Kid Pirates"],
    tags: ["removal", "kid-pirates"],
    description: "Slash. Counter +1000. KO a Character cost 5 or less when KO'd with DON!!.",
  },
  {
    id: "op-op01_109",
    name: "Who's Who",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["animal-kingdom"],
    description: "Slash. Counter +1000. Gains +1000 power if you have 8 or more DON!!.",
  },
  {
    id: "op-op01_110",
    name: "Fukurokuju",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 6,
    power: 8000,
    archetype: ["Land of Wano", "Animal Kingdom Pirates"],
    tags: ["boss", "land-of-wano", "animal-kingdom"],
    description: "Special. Counter +1000.",
  },
  {
    id: "op-op01_111",
    name: "Black Maria",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["blocker", "animal-kingdom"],
    description: "Special. Counter +1000. Blocker. Gains +1000 power when blocking.",
  },
  {
    id: "op-op01_112",
    name: "Page One",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["animal-kingdom"],
    description: "Strike. Counter +1000. Can attack active Characters.",
  },
  {
    id: "op-op01_113",
    name: "Holedem",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Special. Counter +1000. Add a rested DON!! when KO'd.",
  },
  {
    id: "op-op01_114",
    name: "X.Drake",
    game: "onepiece",
    type: "Character",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 5000,
    archetype: ["Navy", "Drake Pirates"],
    tags: ["navy"],
    description: "Slash. Counter +2000. Return 1 DON!! to deck; opponent trashes a card.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 PURPLE EVENTS
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_115",
    name: "Elephant's Marchoo",
    game: "onepiece",
    type: "Event",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 4,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["removal", "animal-kingdom"],
    description: "KO a Character cost 2 or less; add an active DON!!.",
  },
  {
    id: "op-op01_116",
    name: "Artificial Devil Fruit SMILE",
    game: "onepiece",
    type: "Event",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Play a SMILE Character cost 3 or less.",
  },
  {
    id: "op-op01_117",
    name: "Sheep's Horn",
    game: "onepiece",
    type: "Event",
    color: "Purple",
    rarity: "Common",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["Animal Kingdom Pirates", "SMILE"],
    tags: ["animal-kingdom"],
    description: "Rest an opponent's Character cost 6 or less.",
  },
  {
    id: "op-op01_118",
    name: "Ulti-Mortar",
    game: "onepiece",
    type: "Event",
    color: "Purple",
    rarity: "Uncommon",
    set: "OP-01",
    setCode: "OP01",
    cost: 1,
    archetype: ["Animal Kingdom Pirates"],
    tags: ["draw", "animal-kingdom"],
    description: "Return 2 DON!! to deck; give a Character +2000 power; draw a card.",
  },
  {
    id: "op-op01_119",
    name: "Thunder Bagua",
    game: "onepiece",
    type: "Event",
    color: "Purple",
    rarity: "Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 2,
    archetype: ["The Four Emperors", "Animal Kingdom Pirates"],
    tags: ["four-emperors", "animal-kingdom"],
    description: "Give a Character +4000 power; add a DON!! if you have 2 or fewer Life cards.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP01 SECRET RARES
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op01_120",
    name: "Shanks",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Secret Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 9,
    power: 10000,
    archetype: ["The Four Emperors", "Red-Haired Pirates"],
    tags: ["boss", "rush", "secret-rare", "four-emperors"],
    description: "Slash. Rush. Opponent's Blockers with 2000 power or less cannot be activated.",
  },
  {
    id: "op-op01_121",
    name: "Yamato",
    game: "onepiece",
    type: "Character",
    color: "Green",
    rarity: "Secret Rare",
    set: "OP-01",
    setCode: "OP01",
    cost: 5,
    power: 5000,
    archetype: ["Land of Wano"],
    tags: ["secret-rare", "land-of-wano"],
    description: "Strike. Counter +1000. Treated as Oden; Double Attack; Banish on KO.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ST01 SET
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-st01_001",
    name: "Monkey.D.Luffy",
    game: "onepiece",
    type: "Leader",
    color: "Red",
    rarity: "Leader",
    set: "ST-01",
    setCode: "ST01",
    power: 5000,
    life: 5,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["leader", "straw-hat"],
    description: "Leader – Supernovas/Straw Hat Crew. Give a Leader or Character a rested DON!!.",
  },
  {
    id: "op-st01_002",
    name: "Usopp",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 2,
    power: 2000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Ranged. Counter +1000. Opponent's Blockers with 5000 or more power cannot be activated when this attacks.",
  },
  {
    id: "op-st01_003",
    name: "Karoo",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 1,
    power: 3000,
    archetype: ["Animal", "Alabasta"],
    tags: [],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-st01_004",
    name: "Sanji",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 2,
    power: 4000,
    archetype: ["Straw Hat Crew"],
    tags: ["rush", "straw-hat"],
    description: "Strike. Rush when you attach 2 or more DON!! to this Character.",
  },
  {
    id: "op-st01_005",
    name: "Jinbe",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 3,
    power: 5000,
    archetype: ["Fish-Man", "Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Strike. Give another Character +1000 power when attacking.",
  },
  {
    id: "op-st01_006",
    name: "Tony Tony.Chopper",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 1,
    power: 1000,
    archetype: ["Animal", "Straw Hat Crew"],
    tags: ["blocker", "straw-hat"],
    description: "Strike. Blocker.",
  },
  {
    id: "op-st01_007",
    name: "Nami",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 1,
    power: 1000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Special. Give a rested DON!! to a Character.",
  },
  {
    id: "op-st01_008",
    name: "Nico Robin",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 3,
    power: 5000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Wisdom. Counter +1000.",
  },
  {
    id: "op-st01_009",
    name: "Nefertari Vivi",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 2,
    power: 4000,
    archetype: ["Alabasta"],
    tags: [],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-st01_010",
    name: "Franky",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 4,
    power: 6000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-st01_011",
    name: "Brook",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 2,
    power: 3000,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Slash. Counter +2000. Give 2 rested DON!! to Characters.",
  },
  {
    id: "op-st01_012",
    name: "Monkey.D.Luffy",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "ST-01",
    setCode: "ST01",
    cost: 5,
    power: 6000,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["rush", "straw-hat"],
    description: "Strike. Rush. Opponent's Blockers cannot be activated when this attacks.",
  },
  {
    id: "op-st01_013",
    name: "Roronoa Zoro",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "ST-01",
    setCode: "ST01",
    cost: 3,
    power: 5000,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Slash. Gains +1000 power.",
  },
  {
    id: "op-st01_014",
    name: "Guard Point",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 1,
    archetype: ["Animal", "Straw Hat Crew"],
    tags: ["counter-event", "straw-hat"],
    description: "Counter +3000.",
  },
  {
    id: "op-st01_015",
    name: "Gum-Gum Jet Pistol",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 4,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["removal", "straw-hat"],
    description: "KO an opponent's Character cost 6 or less.",
  },
  {
    id: "op-st01_016",
    name: "Diable Jambe",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Common",
    set: "ST-01",
    setCode: "ST01",
    cost: 1,
    archetype: ["Straw Hat Crew"],
    tags: ["straw-hat"],
    description: "Prevent an opponent's Blocker from being activated.",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OP02 SET
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "op-op02_001",
    name: "Edward.Newgate",
    game: "onepiece",
    type: "Leader",
    color: "Red",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 6000,
    life: 6,
    archetype: ["The Four Emperors", "Whitebeard Pirates"],
    tags: ["leader", "draw", "four-emperors", "whitebeard"],
    description: "Leader – The Four Emperors/Whitebeard Pirates. Add a Life card to hand at end of turn.",
  },
  {
    id: "op-op02_002",
    name: "Monkey.D.Garp",
    game: "onepiece",
    type: "Leader",
    color: "Red/Black",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 5000,
    life: 4,
    archetype: ["Navy"],
    tags: ["leader", "navy"],
    description: "Leader – Navy. Reduce opponent Character cost when given DON!!.",
  },
  {
    id: "op-op02_003",
    name: "Atmos",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-02",
    setCode: "OP02",
    cost: 4,
    power: 6000,
    archetype: ["Whitebeard Pirates"],
    tags: ["whitebeard"],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-op02_004",
    name: "Edward.Newgate",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 9,
    power: 10000,
    archetype: ["The Four Emperors", "Whitebeard Pirates"],
    tags: ["boss", "removal", "four-emperors", "whitebeard"],
    description: "Special. Leader gains +2000 power; KO an opponent's Character cost 3 or less when attacking.",
  },
  {
    id: "op-op02_005",
    name: "Curly.Dadan",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Uncommon",
    set: "OP-02",
    setCode: "OP02",
    cost: 2,
    power: 3000,
    archetype: ["Mountain Bandits"],
    tags: ["search"],
    description: "Slash. Counter +1000. Search deck for a red Character cost 1 or less.",
  },
  {
    id: "op-op02_006",
    name: "Koby",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 2,
    power: 2000,
    archetype: ["Navy"],
    tags: ["search", "navy"],
    description: "Strike. Counter +2000. Rest to look at top 5 cards and add a Navy card to hand.",
  },
  {
    id: "op-op02_007",
    name: "Sabo",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 6,
    power: 7000,
    archetype: ["Revolutionary Army"],
    tags: ["rush"],
    description: "Strike. Rush. Set up to 2 Characters as active when attacking.",
  },
  {
    id: "op-op02_008",
    name: "Portgas.D.Ace",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Super Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 5,
    power: 6000,
    archetype: ["Spade Pirates", "Whitebeard Pirates"],
    tags: ["rush", "removal", "whitebeard"],
    description: "Special. Rush. KO an opponent's Character cost 4 or less when attacking.",
  },
  {
    id: "op-op02_009",
    name: "Vista",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 4,
    power: 5000,
    archetype: ["Whitebeard Pirates"],
    tags: ["whitebeard"],
    description: "Slash. Counter +1000.",
  },
  {
    id: "op-op02_010",
    name: "Rakuyo",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Common",
    set: "OP-02",
    setCode: "OP02",
    cost: 3,
    power: 4000,
    archetype: ["Whitebeard Pirates"],
    tags: ["whitebeard"],
    description: "Strike. Counter +1000.",
  },
  {
    id: "op-op02_011",
    name: "Whitebeard Pirates",
    game: "onepiece",
    type: "Event",
    color: "Red",
    rarity: "Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 3,
    archetype: ["Whitebeard Pirates"],
    tags: ["search", "whitebeard"],
    description: "Play a Whitebeard Pirates Character cost 6 or less from deck.",
  },
  {
    id: "op-op02_012",
    name: "Shanks",
    game: "onepiece",
    type: "Character",
    color: "Red",
    rarity: "Secret Rare",
    set: "OP-02",
    setCode: "OP02",
    cost: 9,
    power: 10000,
    archetype: ["The Four Emperors", "Red-Haired Pirates"],
    tags: ["boss", "rush", "secret-rare", "four-emperors"],
    description: "Slash. Rush. Opponent's Blockers with 2000 power or less cannot be activated.",
  },
  {
    id: "op-op02_026",
    name: "Monkey.D.Luffy",
    game: "onepiece",
    type: "Leader",
    color: "Blue",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 5000,
    life: 4,
    archetype: ["Supernovas", "Straw Hat Crew"],
    tags: ["leader", "search", "straw-hat"],
    description: "Leader – Supernovas/Straw Hat Crew. Look at top 5 cards; play a Character cost 5 or less.",
  },
  {
    id: "op-op02_049",
    name: "Akainu",
    game: "onepiece",
    type: "Leader",
    color: "Black",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 5000,
    life: 5,
    archetype: ["Navy"],
    tags: ["leader", "removal", "navy"],
    description: "Leader – Navy. KO an opponent's Character cost 4 or less at the start of your turn.",
  },
  {
    id: "op-op02_072",
    name: "Charlotte Linlin",
    game: "onepiece",
    type: "Leader",
    color: "Yellow",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 6000,
    life: 4,
    archetype: ["The Four Emperors", "Big Mom Pirates"],
    tags: ["leader", "draw", "four-emperors"],
    description: "Leader – The Four Emperors/Big Mom Pirates. Add a card from Life area or draw a card.",
  },
  {
    id: "op-op02_099",
    name: "Marshall.D.Teach",
    game: "onepiece",
    type: "Leader",
    color: "Black/Yellow",
    rarity: "Leader",
    set: "OP-02",
    setCode: "OP02",
    power: 5000,
    life: 4,
    archetype: ["The Four Emperors", "Blackbeard Pirates"],
    tags: ["leader", "four-emperors"],
    description: "Leader – The Four Emperors/Blackbeard Pirates. Add a rested DON!! when a Character is played.",
  },
];
